export type ReviewCategory = "auto" | "handyman" | "exterior";

export type Review = {
  id: string;
  author: string;
  city: string;
  rating: number;
  text: string;
  service: string;
  category: ReviewCategory;
  date: string;
  relativeTime: string;
};

export const reviewStats = {
  averageRating: 4.9,
  totalReviews: 52,
  fiveStarPercent: 94,
} as const;

export const reviews: Review[] = [
  {
    id: "r1",
    author: "James R.",
    city: "Crystal River",
    rating: 5,
    text: "Michael came to my driveway and fixed my brakes the same day I called. No tow truck, no waiting at a shop. Honest price and he explained everything before he started. Will definitely use Infinity Mobile again.",
    service: "Brake Repair",
    category: "auto",
    date: "2026-05-18",
    relativeTime: "3 weeks ago",
  },
  {
    id: "r2",
    author: "Sarah M.",
    city: "Inverness",
    rating: 5,
    text: "Had a check engine light that two other places couldn't figure out. Michael diagnosed it in under an hour at my office parking lot. Straight answers, no upselling. This is how mobile mechanic service should work.",
    service: "Diagnostics",
    category: "auto",
    date: "2026-05-02",
    relativeTime: "1 month ago",
  },
  {
    id: "r3",
    author: "David K.",
    city: "Beverly Hills",
    rating: 5,
    text: "A/C went out in the middle of June and Michael had it blowing cold again by that afternoon. Showed up on time, LLC insured, and the bill was exactly what he quoted on the phone.",
    service: "A/C Repair",
    category: "auto",
    date: "2026-04-21",
    relativeTime: "7 weeks ago",
  },
  {
    id: "r4",
    author: "Linda P.",
    city: "Homosassa",
    rating: 5,
    text: "Used Infinity Mobile for screen repairs on our pool enclosure and a few interior doors. Clean work, fair pricing, and I didn't have to coordinate three different contractors. One call handled it all.",
    service: "Screen Repair",
    category: "handyman",
    date: "2026-04-08",
    relativeTime: "2 months ago",
  },
  {
    id: "r5",
    author: "Marcus T.",
    city: "Lecanto",
    rating: 5,
    text: "Michael did a full tune-up on my F-150 at the job site. Filters, plugs, fluid check — truck runs noticeably smoother. Professional setup and he left the work area cleaner than he found it.",
    service: "Tune-Up",
    category: "auto",
    date: "2026-03-29",
    relativeTime: "2 months ago",
  },
  {
    id: "r6",
    author: "Karen W.",
    city: "Crystal River",
    rating: 4,
    text: "Great handyman work on some shelving and door hardware. Took a little longer to schedule than I hoped because he was booked, but the quality was worth the wait. Very thorough.",
    service: "Handyman",
    category: "handyman",
    date: "2026-03-14",
    relativeTime: "3 months ago",
  },
  {
    id: "r7",
    author: "Tony B.",
    city: "Inverness",
    rating: 5,
    text: "Pressure washed my driveway and back patio — looked brand new. Showed up when he said he would and the price beat every quote I got locally. Already booked him for the fence next month.",
    service: "Pressure Washing",
    category: "exterior",
    date: "2026-02-28",
    relativeTime: "3 months ago",
  },
  {
    id: "r8",
    author: "Rachel H.",
    city: "Beverly Hills",
    rating: 5,
    text: "My Honda wouldn't start before work. Michael tested the battery and alternator right in my cul-de-sac and had me running in 45 minutes. Saved my morning and probably a tow fee too.",
    service: "Electrical / No-Start",
    category: "auto",
    date: "2026-02-11",
    relativeTime: "4 months ago",
  },
  {
    id: "r9",
    author: "Greg S.",
    city: "Homosassa",
    rating: 5,
    text: "VCT flooring install in our small office turned out flawless. Michael prepped the subfloor right, laid the tile precisely, and finished on schedule. Insured and professional — highly recommend.",
    service: "VCT Flooring",
    category: "handyman",
    date: "2026-01-22",
    relativeTime: "4 months ago",
  },
  {
    id: "r10",
    author: "Amanda C.",
    city: "Crystal River",
    rating: 5,
    text: "Called for a quote on custom exhaust work and Michael walked me through options without pushing the most expensive route. Quality install and my Mustang sounds incredible. Real performance shop feel.",
    service: "Custom Aftermarket",
    category: "auto",
    date: "2026-01-09",
    relativeTime: "5 months ago",
  },
  {
    id: "r11",
    author: "Robert N.",
    city: "Inverness",
    rating: 5,
    text: "Transmission was slipping and I dreaded the repair bill. Michael diagnosed it honestly, explained what was urgent vs what could wait, and fixed what I approved. No scare tactics — just facts.",
    service: "Transmission Service",
    category: "auto",
    date: "2025-12-15",
    relativeTime: "6 months ago",
  },
  {
    id: "r12",
    author: "Diane F.",
    city: "Lecanto",
    rating: 5,
    text: "We use Infinity Mobile for both our cars and small home projects. Having one trusted local business for auto and handyman work in Citrus County is a huge convenience. Michael is the real deal.",
    service: "Auto + Handyman",
    category: "handyman",
    date: "2025-11-30",
    relativeTime: "6 months ago",
  },
  {
    id: "r13",
    author: "Chris L.",
    city: "Beverly Hills",
    rating: 4,
    text: "Solid engine diagnostic on my Tahoe. Found a vacuum leak another shop missed. Price was fair and communication was good throughout. Would use again for sure.",
    service: "Engine Diagnostics",
    category: "auto",
    date: "2025-11-08",
    relativeTime: "7 months ago",
  },
  {
    id: "r14",
    author: "Patricia G.",
    city: "Crystal River",
    rating: 5,
    text: "Michael pressure washed our home exterior and it made a huge difference before we listed the house. Fast, careful around landscaping, and the siding looks years newer. Great value.",
    service: "Pressure Washing",
    category: "exterior",
    date: "2025-10-19",
    relativeTime: "8 months ago",
  },
  {
    id: "r15",
    author: "Mike D.",
    city: "Homosassa",
    rating: 5,
    text: "Engine swap consultation and install support for my project truck. Michael knows his stuff — patient with questions and meticulous with the work. Citrus County needed a mobile shop like this.",
    service: "Engine Swap",
    category: "auto",
    date: "2025-09-27",
    relativeTime: "8 months ago",
  },
];

export const reviewFilters = [
  { id: "all" as const, label: "All Reviews" },
  { id: "auto" as const, label: "Auto Repair" },
  { id: "handyman" as const, label: "Handyman" },
  { id: "exterior" as const, label: "Exterior" },
];
